# Generated by Django 4.2.4 on 2023-10-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=105)),
                ('notes', models.TextField(max_length=1000)),
            ],
        ),
    ]
